apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitster-app
spec:
  template:
    spec:
      containers:
        - name: hitster-app
          # Updated by .github/workflows/commit.nuxt.yaml.
          image: >-
            ghcr.io/simonbrundin/hitster@sha256:62e623c85ce92342d74f0f03c674327ed8da5449086a906409911a4d0b1b46d8
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_URL
              value: "https://hitster.simonbrundin.com"
            - name: NITRO_APP_URL
              value: "https://hitster.simonbrundin.com"
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hitster-auth
                  key: SPOTIFY_CLIENT_ID
            - name: NITRO_SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hitster-auth
                  key: SPOTIFY_CLIENT_ID
            - name: NITRO_PUBLIC_SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hitster-auth
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hitster-auth
                  key: SPOTIFY_CLIENT_SECRET
            - name: NITRO_SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hitster-auth
                  key: SPOTIFY_CLIENT_SECRET
