name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: src/nuxt

      - name: Lint
        run: bun run lint
        working-directory: src/nuxt

      - name: Typecheck
        run: bun run typecheck
        working-directory: src/nuxt

      - name: Test
        run: bun test
        working-directory: src/nuxt

      - name: Build
        run: bun run build
        working-directory: src/nuxt

      - name: Audit production dependencies
        run: bun audit --production
        working-directory: src/nuxt
