apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: hitster
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5J+QC3gb6jtCgVuntxcgEymdmp2e+2aLY94w2jXaAaSzRNfKNw2F8CRd1/Qi4KXJANI6wkleINl41raDEXgEz/v0ZcZyW50/XfyAvcCrLcj1L2z6m4CvfDix+6ImaIjHahtxtg0iz3JfXKbu8fFVBZa2RLm//TXeZTrb6YcC2g1RkvqRnf1xheLt6Fg=,iv:ytX0wY8U6sFrrtUD5cc7w5vPjpvRFhyBt9x0BQPerQY=,tag:XJ987FHf46Du2mFJOmhs5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFlER3REVjFZdWp1SlFj
            SnVvck1CemZzY3NvMGdvMWxQK2hkV1FYYkNrCnI0WFZhN2U5d1lDTm4ycm1VZits
            bDRuUUNNTE9xcWV5WEZzMUlUU09zR2MKLS0tIERvdUVGUkFDQ0orZ3plTXU4RFh1
            NjBnalpBNXlSQUxmNkZ5OWVUZkhXd1UKX0aZiNCty6tHsyTBGWQYujRuZoax+vPd
            7CWEi5pw/8g/eNkwNS2uvka3ql6QyN296k/MU/zCZuAV3V5i3xW5Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T10:26:53Z"
    mac: ENC[AES256_GCM,data:0C3gSnTU7uFu50xDdqVR26qYfXmvMbosb8jjbFCFIhaQRShJQkAtRIFgXzFXL0cCPBZszTwXxjEcV//WsehJ1v7n6PRKh/fvl5q6t8CtN57jerjZD/lOJQ7Z29LP/YqLGzI2dSkmZpwP+JdN123GJTPgfsxnochjR6NbKnSiEzk=,iv:uqXV28Qntv9prkau07EFv14kgla5HkZaTj4cuHni9gE=,tag:/3EqJ22JV1eFx4xIwNvN3Q==,type:str]
    version: 3.13.3
