# SOPS-krypterad hemlighet för hitster
# Använd: sops -e secrets/auth.yaml > secrets/auth.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hitster-auth
    namespace: hitster
type: Opaque
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:YPm7K2FQr9o5DOPjTCdvWfQ2MPwGVKWic5NyHgk=,iv:nZBR6SBtcVgjT0seiq4HWGxvj54Boy+Si/4vy02wK1o=,tag:WaWuIGPK2mshf9AjcXYDmw==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:fojvJeWAx/RMBtdmSerO1xSDILMeh/bUPxJ6kahdDu3j,iv:LED72O3oYdvXLnlPY3PVSiRaJWeM+fsAzKkt7fCcEPc=,tag:hL1pcWpKCV64SeFBD/2H3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVUIwT0d6NTBJazd3MlJM
            bk5XTlJIb1RwQzkybmxTVWwwK2xNNVdSNjIwCmswWlhVa2RCMVc1YUtPSmE1QVhZ
            L1hNbXZxQ2FtbDhub1NrUVZuU1h6clkKLS0tIG9HRFdERmR4ZWVqZUNCbzcvZ2N4
            azl3TzJlRHAvMzVoTlFpTFVCakNFdzAKFnuyUDiuI1cP6uQBxgDDE1+fAQHy4bLk
            YtzVW+ymnaRdtqA0IRiNf+P9YMjGDLEbOkecdQZ+cZztYHCa8oFXVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:15:44Z"
    mac: ENC[AES256_GCM,data:adeArtud9Rtb6+bYf0FhORHthJ4juDMgBwL5KwsM91vq7H/diDBS3Rld0N6zJbap7VmqL9lAmJoLMmxaJROCURfqDjIa+Me1ziCNm35gPpoojTfQGCzfOLSNPN8cOiVHBv4xCRLt9h/ehH9lMmMDDTrLCQ6CgSzNXkx13kNIXvk=,iv:eMJDeodfkArxnoYtbp/y8ozdjdPV6JwD1RyTskF+EzQ=,tag:aHk5amrCR3iz4+HLKuUMUw==,type:str]
    version: 3.13.3
