apiVersion: v1
data:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:m0t9nhAnzMV4FirdUFXXVBmLPhbpSByw1tNcCbth5vpy/MRldbHq6Sy8POU=,iv:WM7tAojatYNfsrPN1aPLlxGwHa/ERZ7+Lhsk/GaWM/E=,tag:AeUZTmynPw8Q0W2XF0j57g==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:iH34dTBUzYoEGA//wALFYuRzZYabRMLLaomngfyaWDBitOpmqqrvfmCsfKA=,iv:5TkTeu+av17rDcwD3x5lZI3AmwiMhwYAzN+bHkh/wAI=,tag:6dYaVVaBTs0rzC6RO4yfog==,type:str]
kind: Secret
metadata:
    name: hitster-auth
    namespace: hitster
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSS84QUVDZ3BhVDJjYm1B
            dVdpMWtackFpRXEyeTNReUhVY3ZCOXVzZmxRClc3cUsycEJZT3QzaStyYWwwbVVK
            UVZDQ3RyeEx4NWxUM3FITXQwSEZyWXcKLS0tIGJYcUgxYmF5THBiYmtDVStzMy94
            bjJLU2FqdU1zRW5aZTloSVkrcHF1aE0KQC5i/GoaxW0wT+df04jYUhwV56yeLTwK
            OpnTKrZ3cA07YFjW4/GCHbu3TF0yApKT9ex/JJemFpRVcoO1phRpIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T10:18:16Z"
    mac: ENC[AES256_GCM,data:j603vLyeHEbzZt/wA9xaqP+D4H7LU1ECcSdaVfWLKZdg9DtogxzrAvHf4F2fxBFJF9T346+9P7imVE7yKyK0tG1NMeSclCPUiATrgGXY3EgcKElZaAaH93DZcZzaS6q05glimiVURGKkQHmPng/ifZu6BWRUYq1c98ulefOk3Q8=,iv:Fh4i+J3799W47AbE9BtyKwDLhcdtW5y7giY5t2NYEfg=,tag:5bJrfvSj6aTtaHLZgwJqIQ==,type:str]
    version: 3.13.3
